server.port: 9005
spring:
  application:
    name: board-article-read-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  board-article-service:
    url: ${ARTICLE_SERVICE_URL}
  board-comment-service:
    url: ${COMMENT_SERVICE_URL}
  board-like-service:
    url: ${LIKE_SERVICE_URL}
  board-view-service:
    url: ${VIEW_SERVICE_URL}